dist: focal

language: python

install:
  - pip install --upgrade pip > /dev/null
  - pip install -r requirements.txt > /dev/null

script:
  - cd ./tests/ && pytest && cd ..

after_success:
 - bash <(curl -s https://codecov.io/bash)